language: node_js
addons:
  apt:
    packages:
    - libgconf-2-4
cache:
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - $(npm bin)/cypress verify
notifications:
  email: true
node_js:
  - '10'
script:
  - npm run lint
  - npm run transpile
  # you can simply run the tests
  - npm test -- --record false
  # you can record the tests on Cypress Dashboard
  # - npm test -- --record
  # and you can run the tests with Percy.io visual testing included
  # - npm run percy:test -- --record

after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
